
export {default as Home} from './Home'
export {default as SignIn} from './SignIn'
export {default as SignUp} from './SignUp'
export {default as AddArt} from './AddArt'
export {default as MainPage} from './MainPage'
export {default as Products} from './products'
export {default as Kart} from './Cart'
export {default as Payment} from './PaymentPage'
export {default as Admin} from './AdminSignIn'
export {default as AdminDashboard} from './AdminDashboard'
export {default as AdminArtPage} from './AdminArtPage'
export {default as EditArtPage} from './EditArtPage'
export {default as AdminArtistPage} from './AdminArtistPage'
export {default as AddArtistPage} from './AddArtistPage'
export {default as EditArtistPage} from './EditArtistPage'